#ifndef KEYCODE_HEADER
#define KEYCODE_HEADER

#define		_C_A			0x40041  // ^a
#define		_C_B			0x40042
#define		_C_C			0x40043
#define		_C_D			0x40044
#define		_C_E			0x40045
#define		_C_F			0x40046
#define		_C_G			0x40047
#define		_C_H			0x40048
#define		_C_I			0x40049
#define		_C_J			0x4004A
#define		_C_K			0x4004B
#define		_C_L			0x4004C
#define		_C_M			0x4004D
#define		_C_N			0x4004E
#define		_C_O			0x4004F
#define		_C_P			0x40050
#define		_C_Q			0x40051
#define		_C_R			0x40052
#define		_C_S			0x40053
#define		_C_T			0x40054
#define		_C_U			0x40055
#define		_C_V			0x40056
#define		_C_W			0x40057
#define		_C_X			0x40058
#define		_C_Y			0x40059
#define		_C_Z			0x4005A

#define		_A_A			0x20061  // @a
#define		_A_B			0x20062
#define		_A_C			0x20063
#define		_A_D			0x20064
#define		_A_E			0x20065
#define		_A_F			0x20066
#define		_A_G			0x20067
#define		_A_H			0x20068
#define		_A_I			0x20069
#define		_A_J			0x2006A
#define		_A_K			0x2006B
#define		_A_L			0x2006C
#define		_A_M			0x2006D
#define		_A_N			0x2006E
#define		_A_O			0x2006F
#define		_A_P			0x20070
#define		_A_Q			0x20071
#define		_A_R			0x20072
#define		_A_S			0x20073
#define		_A_T			0x20074
#define		_A_U			0x20075
#define		_A_V			0x20076
#define		_A_W			0x20077
#define		_A_X			0x20078
#define		_A_Y			0x20079
#define		_A_Z			0x2007A

#define		_F1			0xF00   // F1
#define		_F2			0x1000
#define		_F3			0x1100
#define		_F4			0x1200
#define		_F5			0x1300
#define		_F6			0x1400
#define		_F7			0x1500
#define		_F8			0x1600
#define		_F9			0x1700
#define		_F10		0x1800
#define		_F11		0x1900
#define		_F12		0x1A00

#define		_SF1		0x10F00   // #F1
#define		_SF2		0x11000
#define		_SF3		0x11100
#define		_SF4		0x11200
#define		_SF5		0x11300
#define		_SF6		0x11400
#define		_SF7		0x11500
#define		_SF8		0x11600
#define		_SF9		0x11700
#define		_SF10		0x11800
#define		_SF11		0x11900
#define		_SF12		0x11A00

#define		_CF1		0x40F00   // ^F1
#define		_CF2		0x41000
#define		_CF3		0x41100
#define		_CF4		0x41200
#define		_CF5		0x41300
#define		_CF6		0x41400
#define		_CF7		0x41500
#define		_CF8		0x41600
#define		_CF9		0x41700
#define		_CF10		0x41800
#define		_CF11		0x41900
#define		_CF12		0x41A00

#define		_SCF1		0x50F00   // #^F1
#define		_SCF2		0x51000
#define		_SCF3		0x51100
#define		_SCF4		0x51200
#define		_SCF5		0x51300
#define		_SCF6		0x51400
#define		_SCF7		0x51500
#define		_SCF8		0x51600
#define		_SCF9		0x51700
#define		_SCF10		0x51800
#define		_SCF11		0x51900
#define		_SCF12		0x51A00

#define		_C_AP			0x40060 // ^`
#define		_C_1			0x40031 // ^`
#define		_C_2			0x40032 // ^`
#define		_C_3			0x40033 // ^`
#define		_C_4			0x40034 // ^`
#define		_C_5			0x40035 // ^`
#define		_C_6			0x40036 // ^`
#define		_C_7			0x40037 // ^`
#define		_C_8			0x40038 // ^`
#define		_C_9			0x40039 // ^`
#define		_C_0			0x40030 // ^`
#define		_C_MS			0x4002D // ^`
#define		_C_EQ			0x4003D // ^`
#define		_C_BS			0x40200 // ^`
#define		_C_TAB			0x40400 // ^`
#define		_C_INS			0x40A00 // ^`
#define		_C_DEL			0x40100 // ^`
#define		_C_BRKL			0x4005B // ^[
#define		_C_BRKR			0x4005D // ^]
//#define		_C_|			0x4005C // ^`
#define		_C_CR			0x40500 // ^`
#define		_C_HOME			0x40B00 // ^`
#define		_C_PGUP			0x40D00 // ^`
#define		_C_PGDN			0x40E00 // ^`
#define		_C_END			0x40C00 // ^`
#define		_C_UP			0x40600 // ^`
#define		_C_DN			0x40700 // ^`
#define		_C_LEFT			0x40800 // ^`
#define		_C_RIGHT		0x40900 // ^`

#define		_A_AP			0x20060 // ^`
#define		_A_1			0x20031 // ^`
#define		_A_2			0x20032 // ^`
#define		_A_3			0x20033 // ^`
#define		_A_4			0x20034 // ^`
#define		_A_5			0x20035 // ^`
#define		_A_6			0x20036 // ^`
#define		_A_7			0x20037 // ^`
#define		_A_8			0x20038 // ^`
#define		_A_9			0x20039 // ^`
#define		_A_0			0x20030 // ^`
#define		_A_MS			0x2002D // ^`
#define		_A_BS			0x20200 // ^`
#define		_A_TAB			0x20400 // ^`
#define		_A_BRKL			0x2005B // ^[
#define		_A_BRKR			0x2005D // ^]
//#define		_A_|			0x2005C // ^`
#define		_A_CR			0x20500 // ^`

#define		_S_ESC			0x10300
#define		_S_BS			0x10200 // ^`
#define		_S_TAB			0x10400 // ^`
#define		_S_INS			0x10A00 // ^`
#define		_S_DEL			0x10100 // ^`
#define		_S_CR			0x10500 // ^`
#define		_S_HOME			0x10B00 // ^`
#define		_S_PGUP			0x10D00 // ^`
#define		_S_PGDN			0x10E00 // ^`
#define		_S_END			0x10C00 // ^`
#define		_S_UP			0x10600 // ^`
#define		_S_DN			0x10700 // ^`
#define		_S_LEFT			0x10800 // ^`
#define		_S_RIGHT		0x10900 // ^`

#define		_ESC			0x300
#define		_BS				0x200 // ^`
#define		_TAB			0x400 // ^`
#define		_INS			0xA00 // ^`
#define		_DEL			0x100 // ^`
#define		_CR				0x500 // ^`
#define		_HOME			0xB00 // ^`
#define		_PGUP			0xD00 // ^`
#define		_PGDN			0xE00 // ^`
#define		_END			0xC00 // ^`
#define		_UP				0x600 // ^`
#define		_DN				0x700 // ^`
#define		_LEFT			0x800 // ^`
#define		_RIGHT			0x900 // ^`

#endif
