#ifndef		ZEROSET_H
#define		ZEROSET_H
/**************************************************************************/
/* LabWindows/CVI User Interface Resource (UIR) Include File              */
/* Copyright (c) National Instruments 2002. All Rights Reserved.          */
/*                                                                        */
/* WARNING: Do not add to, delete from, or otherwise modify the contents  */
/*          of this include file.                                         */
/**************************************************************************/

#include <userint.h>

#ifdef __cplusplus
    extern "C" {
#endif

     /* Panels and Controls: */

#define  ZEROSET                         1
#define  ZEROSET_CLOSEZEROSET            2
#define  ZEROSET_ZEROSETDATA             3
#define  ZEROSET_DOWNZEROSET             4
#define  ZEROSET_DOZEROSET               5
#define  ZEROSET_UPZEROSET               6


     /* Menu Bars, Menus, and Menu Items: */

          /* (no menu bars in the resource file) */


     /* (no callbacks specified in the resource file) */ 


#ifdef __cplusplus
    }
#endif
#endif
